package com.acme.homework_pam_sebastian_morales;

import java.util.HashMap;
import java.util.Map;

import org.kie.api.runtime.process.WorkItem;
import org.kie.api.runtime.process.WorkItemHandler;
import org.kie.api.runtime.process.WorkItemManager;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WaitWIH implements WorkItemHandler {

    static final long serialVersionUID = 1L;

    private Integer minutos;
    
    public WaitWIH(Integer minutos) {
    	this.minutos = minutos;
    }

    @Override
	public void executeWorkItem(WorkItem workItem, WorkItemManager manager) {
    	try {
    		System.out
				.println("Esperando " + minutos + " minutos para continuar la siguiente peticion");
		
		
			Thread.sleep(minutos *   // minutes to sleep
			         60 *   // seconds to a minute
			         1000);
			manager.completeWorkItem(workItem.getId(), workItem.getParameters());
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}				
	}

	@Override
	public void abortWorkItem(WorkItem workItem, WorkItemManager manager) {

	}

}